# Generated by Django 6.0.7 on 2026-08-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='telephone_secondaire',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
